-define(WERLD_REQUEST_TYPE_AUTHENTICATE, 0:8/unsigned).
-define(WERLD_REQUEST_TYPE_REGISTER,     1:8/unsigned).
-define(WERLD_REQUEST_TYPE_MAP,          3:8/unsigned).
-define(WERLD_REQUEST_TYPE_PLAYER,       4:8/unsigned).
-define(WERLD_REQUEST_TYPE_PLAYERS,      5:8/unsigned).
-define(WERLD_REQUEST_TYPE_MESSAGE,      6:8/unsigned).
