-define(WERLD_RESPONSE_TYPE_REGISTER, 0:8/unsigned).
-define(WERLD_RESPONSE_TYPE_PLAYERS,  1:8/unsigned).
-define(WERLD_RESPONSE_TYPE_MESSAGE,  2:8/unsigned).
-define(WERLD_RESPONSE_TYPE_MAP,      3:8/unsigned).
